version: '3.1'

services:

  db:
    image: postgres
    restart: always
    env_file:
      - ./docker-db-password.txt
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080